### ISSUE TITLE
Multiple items per transactions and retrieving patterns

### ISSUE THREAD

**Issue by demodw** [chuanconggao/PrefixSpan-py#7]
Hi,

is it possible to specify multiple items per transaction?

For instance, 

`[
 [0, [1,2], 3],
 [0, 1, 3],
 [4, 5, 0, [1,2], 3]
]
`

Would also have the pattern [0, [1,2], 3] observed two times. Second, is it possible to specify that the framework should return _all_ patterns that meet the minimum support criteria, without knowing how many there are in advance?

Thanks for a great tool! It seems to be super fast, even for millions of sequences.

**Comment by chuanconggao** [comment]
Currently, having multiple items per event is not supported. It is because there are three algorithms, and I prefer adding this kind of support to all of them. This is on the todo list. 

For your second question, the algorithms returns all the frequent (closed/generator) patterns w.r.t. the minimum support threshold.
